---
title: "Oregon_Enrollment_Data_Viz"
author: "Amy Yates"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, dev="ragg_png")
# knitr::opts_chunk$set(fig.width=14)
```

## Data Visualization

This explores some data visualizations using race/ethnicity enrollment data from Oregon school districts.

```{r}
library(tidyverse)
library(janitor)
library(readxl)
library(scales)
library(hrbrthemes)
library(ftplottools)
library(ggtext)
library(ragg)
library(systemfonts)
library(ggalt)
enrollment_by_race_ethnicity <- read_rds("data/enrollment_by_race_ethnicity.rds")
```

```{r}
enrollment_by_race_ethnicity %>%
  filter(district == 'Beaverton SD 48J') %>%
  filter(year == '2018-2019') %>% 
  ggplot(aes(x=percent_of_total_enrollment, y=race_ethnicity)) +
  geom_col()
```
```{r}
enrollment_by_race_ethnicity %>%
  filter(district == 'Beaverton SD 48J') %>%
  filter(year == '2018-2019') %>% 
  ggplot(aes(x=percent_of_total_enrollment, y=reorder(race_ethnicity, percent_of_total_enrollment))) +
  geom_col()
```
```{r}
enrollment_by_race_ethnicity %>%
  filter(district == 'Beaverton SD 48J') %>%
  filter(year == '2018-2019') %>%
  mutate(race_ethnicity = fct_reorder(race_ethnicity, percent_of_total_enrollment)) %>% 
  ggplot(aes(x=percent_of_total_enrollment, y=race_ethnicity)) +
  geom_col()
```
```{r}
enrollment_by_race_ethnicity %>%
  filter(race_ethnicity == 'Hispanic/Latino') %>% 
  pivot_wider(id_cols = c(district_id, district),
              names_from = year,
              values_from = percent_of_total_enrollment) %>% 
  mutate(growth = `2018-2019` - `2017-2018`) %>% 
  arrange(desc(growth))
```

```{r fig.width=14}
highlight <- enrollment_by_race_ethnicity %>% 
  filter(race_ethnicity == 'Hispanic/Latino') %>% 
  filter(district == 'Douglas ESD') %>%
  mutate(percent_display = percent(percent_of_total_enrollment, accuracy=1)) %>% 
  mutate(percent_display = case_when(
    year == '2018-2019' ~ str_glue("{percent_display} increase in Hispanic/Latino enrollment"),
    TRUE ~ percent_display
  ))

# Can get the rgb value and then convert to hex: col2rgb("orange2")
orange2 <- "#EE9A00"
grey85 <- "#D9D9D9"
theme_ay <- function() {
  theme_light(base_family = "Trebuchet MS") +
  theme(axis.title = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_markdown())
}

enrollment_by_race_ethnicity %>%
  filter(race_ethnicity == 'Hispanic/Latino') %>%
  ggplot(aes(x=year, y=percent_of_total_enrollment, group=district)) +
  geom_line(color=grey85) +
  scale_y_continuous(label=percent_format(), limits = c(0,1)) +
  scale_x_discrete(expand = expansion(add=c(.05, .4))) +
  geom_line(data = highlight, inherit.aes = TRUE, color=orange2) +
  geom_text(data = highlight, 
            color=orange2, 
            aes(label=percent_display), 
            hjust=c(1.3, -0.02), 
            family = "Trebuchet MS") +
  labs(title = str_glue("<span style='color: {orange2}'>Douglas ESD</span> saw the largest increase in Hispanic/Latino enrollment in the 2018-2019 school year.")) +
  theme_ay() +
  annotate("text",
           x = 2.02,
           y = .8,
           label = "Grey lines represent all\nOregon school districts.",
           hjust = 0,
           color = "darkgrey",
           family = "Trebuchet MS")

```

```{r}
ggsave("final_plot.png", device = agg_png, width = 14)
```

```{r}
# For a lollipop plot, we need the years in separate columns. We'll also calculate the percent change and keep the top 20
hispanic_summary <- enrollment_by_race_ethnicity %>%
  filter(race_ethnicity == 'Hispanic/Latino') %>% 
  pivot_wider(id_cols = district, names_from = year, values_from = percent_of_total_enrollment) %>% 
  clean_names() %>% 
  mutate(percent_change = abs(x2017_2018-x2018_2019/x2017_2018*100)) %>% 
  arrange(desc(percent_change)) %>% 
  slice(1:20)

hispanic_summary %>%
  ggplot(aes(x = x2017_2018, xend = x2018_2019, y=district, yend = district, group=district)) +
  geom_dumbbell(colour="#a3c4dc", size_x = 3, size_xend = 3, colour_xend="#0e668b", 
                         dot_guide=TRUE, dot_guide_size=0.15) +
  scale_x_continuous(label = percent_format()) +
  labs(title = "Change in Hispanic Enrollment in Oregon from <span style='color:#a3c4dc'>2017</span>-<span style='color:#0e668b'>2018</span>.<br>The 20 districts with the most change all saw increases.") +
  theme_ay()

```

